export const bibleBooks: { [key: string]: string } = {
  // Antiguo Testamento
  'gen': 'Génesis',
  'exo': 'Éxodo',
  'lev': 'Levítico',
  'num': 'Números',
  'deu': 'Deuteronomio',
  'jos': 'Josué',
  'jdg': 'Jueces',
  'rut': 'Rut',
  '1sa': '1 Samuel',
  '2sa': '2 Samuel',
  '1ki': '1 Reyes',
  '2ki': '2 Reyes',
  '1ch': '1 Crónicas',
  '2ch': '2 Crónicas',
  'ezr': 'Esdras',
  'neh': 'Nehemías',
  'est': 'Ester',
  'job': 'Job',
  'psa': 'Salmos',
  'pro': 'Proverbios',
  'ecc': 'Eclesiastés',
  'sng': 'Cantares',
  'isa': 'Isaías',
  'jer': 'Jeremías',
  'lam': 'Lamentaciones',
  'ezk': 'Ezequiel',
  'dan': 'Daniel',
  'hos': 'Oseas',
  'jol': 'Joel',
  'amo': 'Amós',
  'oba': 'Abdías',
  'jon': 'Jonás',
  'mic': 'Miqueas',
  'nam': 'Nahúm',
  'hab': 'Habacuc',
  'zep': 'Sofonías',
  'hag': 'Hageo',
  'zec': 'Zacarías',
  'mal': 'Malaquías',
  
  // Nuevo Testamento
  'mat': 'Mateo',
  'mrk': 'Marcos',
  'luk': 'Lucas',
  'jhn': 'Juan',
  'act': 'Hechos',
  'rom': 'Romanos',
  '1co': '1 Corintios',
  '2co': '2 Corintios',
  'gal': 'Gálatas',
  'eph': 'Efesios',
  'php': 'Filipenses',
  'col': 'Colosenses',
  '1th': '1 Tesalonicenses',
  '2th': '2 Tesalonicenses',
  '1ti': '1 Timoteo',
  '2ti': '2 Timoteo',
  'tit': 'Tito',
  'phm': 'Filemón',
  'heb': 'Hebreos',
  'jas': 'Santiago',
  '1pe': '1 Pedro',
  '2pe': '2 Pedro',
  '1jn': '1 Juan',
  '2jn': '2 Juan',
  '3jn': '3 Juan',
  'jud': 'Judas',
  'rev': 'Apocalipsis',

  // Variantes comunes
  'génesis': 'Génesis',
  'éxodo': 'Éxodo',
  'levítico': 'Levítico',
  'números': 'Números',
  'deuteronomio': 'Deuteronomio',
  'josué': 'Josué',
  'jueces': 'Jueces',
  'rut': 'Rut',
  'samuel': 'Samuel',
  'reyes': 'Reyes',
  'crónicas': 'Crónicas',
  'esdras': 'Esdras',
  'nehemías': 'Nehemías',
  'ester': 'Ester',
  'job': 'Job',
  'salmos': 'Salmos',
  'proverbios': 'Proverbios',
  'eclesiastés': 'Eclesiastés',
  'cantares': 'Cantares',
  'isaías': 'Isaías',
  'jeremías': 'Jeremías',
  'lamentaciones': 'Lamentaciones',
  'ezequiel': 'Ezequiel',
  'daniel': 'Daniel',
  'oseas': 'Oseas',
  'joel': 'Joel',
  'amós': 'Amós',
  'abdías': 'Abdías',
  'jonás': 'Jonás',
  'miqueas': 'Miqueas',
  'nahúm': 'Nahúm',
  'habacuc': 'Habacuc',
  'sofonías': 'Sofonías',
  'hageo': 'Hageo',
  'zacarías': 'Zacarías',
  'malaquías': 'Malaquías',
  'mateo': 'Mateo',
  'marcos': 'Marcos',
  'lucas': 'Lucas',
  'juan': 'Juan',
  'hechos': 'Hechos',
  'romanos': 'Romanos',
  'corintios': 'Corintios',
  'gálatas': 'Gálatas',
  'efesios': 'Efesios',
  'filipenses': 'Filipenses',
  'colosenses': 'Colosenses',
  'tesalonicenses': 'Tesalonicenses',
  'timoteo': 'Timoteo',
  'tito': 'Tito',
  'filemón': 'Filemón',
  'hebreos': 'Hebreos',
  'santiago': 'Santiago',
  'pedro': 'Pedro',
  'judas': 'Judas',
  'apocalipsis': 'Apocalipsis'
};
